# noinspection KubernetesUnknownResourcesInspection
apiVersion: argoproj.io/v1alpha1
# noinspection KubernetesUnknownResourcesInspection
kind: Application
metadata:
  name: prometheus-app1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/prometheus-community/helm-charts.git'
    targetRevision: main
    path: charts/jiralert
  destination:
    namespace: jd
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
