apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-server
  namespace: argocd
spec:
  destination:
    namespace: jd
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/Ealenn/charts'
    targetRevision: HEAD
    chart: echo-server
    version: 'latest'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
