# noinspection KubernetesUnknownResourcesInspection
apiVersion: argoproj.io/v1alpha1
# noinspection KubernetesUnknownResourcesInspection
kind: Application
metadata:
  name: echo-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ealenn/charts.git
    path: charts/echo-server
    targetRevision: master
  destination:
    namespace: jd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
